---
dist: bionic
env:
  global:
    # When changing this, ensure that the Vagrantfile is updated as well
    - VAGRANT_VERSION="2.2.9"
    - BASE_BOX_VAGRANT_VM_ID="base-box-builder.k8s-play.local"
jobs:
  fast_finish: true
  include:
    - name: "Linting"
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/.vagrant.d/boxes
          - $HOME/.vagrant.d/gems
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - /var/lib/docker/overlay2
          - $HOME/.nvm/versions
      language: shell
      before_install:
        - sudo scripts/linux/ci/install-dependencies.sh
        - scripts/linux/ci/install-node.sh
      install:
        - nvm use
        - scripts/linux/ci/install-linting-tools.sh
      script: |
        scripts/linux/ci/lint.sh || exit 1;
        scripts/linux/ci/build-docker-images.sh || exit 1;
      stage: linting_and_docker
      after_script:
        - scripts/linux/ci/diagnostics.sh
      after_failure:
        - scripts/linux/ci/diagnostics.sh  --verbose
    - name: "Build base box and vagrant up"
      env:
        - VAGRANT_DEFAULT_PROVIDER=libvirt
      stage: vagrant-base-box-up
      language: ruby
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/.vagrant.d/boxes
          - $HOME/.vagrant.d/gems
          - $GEM_HOME
          - vendor/bundle
          - $GOPATH/pkg/mod
          - /var/lib/docker/overlay2
          - $HOME/.nvm/versions
      before_install:
        - sudo scripts/linux/ci/install-dependencies.sh
        - scripts/linux/ci/install-node.sh
        - sudo scripts/linux/ci/install-libvirt.sh
        - sudo scripts/linux/ci/install-vagrant.sh
        - sudo scripts/linux/ci/install-vagrant-plugins.sh
        - sudo scripts/linux/ci/generate-env-for-travis.sh
        # Fix permissions after installing vagrant plugins with sudo
        - sudo chown -R "$(id -un)":"$(id -un)" $HOME/.vagrant.d
        # This doesn't have effect if you don't open a new shell
        - sudo adduser "$(id -un)" libvirt
        - sudo adduser "$(id -un)" kvm
      install:
        - gem install bundler
        - bundle install
      before_script:
        - inspec check --chef-license=accept test/inspec/kubernetes-playground
        # Workaround for https://github.com/hashicorp/vagrant/issues/8279
        - chmod a+rx $HOME
        - |
          sudo \
          PATH="$PATH" \
          VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
          scripts/linux/ci/diagnostics.sh
      # Run with sudo because the libvirt socket is owned by the libvirt group,
      # and the current user was added to the group in the current session,
      # so the membership to that group is not yet in effect.
      # Set the PATH to make the installed gems accessible.
      script: |
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant up "$BASE_BOX_VAGRANT_VM_ID"; \
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        VAGRANT_SUPPRESS_OUTPUT="true" \
        scripts/linux/ci/run-inspec-against-host.sh "$BASE_BOX_VAGRANT_VM_ID";
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant package "$BASE_BOX_VAGRANT_VM_ID" \
            --output kubernetes-playground-base.box;
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant provision "$BASE_BOX_VAGRANT_VM_ID" \
            --provision-with diagnostics-verbose;
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant destroy --force "$BASE_BOX_VAGRANT_VM_ID"; \
        time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant box add --force kubernetes-playground-base.box \
            --name ferrarimarco/kubernetes-playground-node;
        timeout 3m time sudo \
        PATH="$PATH" \
        VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
        vagrant up k8s-master-1.k8s-play.local --no-provision;
      after_script:
        - |
          sudo \
          PATH="$PATH" \
          VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
          scripts/linux/ci/diagnostics.sh --vagrant-vm-name "$BASE_BOX_VAGRANT_VM_ID"
      after_failure:
        - |
          sudo \
          PATH="$PATH" \
          VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
          scripts/linux/ci/diagnostics.sh \
            --vagrant-vm-name "$BASE_BOX_VAGRANT_VM_ID"  \
            --vagrant-libvirt-img-path \
              "$HOME"/.vagrant.d/boxes/ferrarimarco-VAGRANTSLASH-kubernetes-playground-node/0/libvirt/box.img \
            --verbose
        - |
          sudo \
          PATH="$PATH" \
          VAGRANT_DEFAULT_PROVIDER="$VAGRANT_DEFAULT_PROVIDER" \
          scripts/linux/ci/diagnostics.sh --vagrant-vm-name k8s-master-1.k8s-play.local --verbose
language: shell
os: linux
services:
  - docker
stages:
  - linting_and_docker
  - vagrant-base-box
  - vagrant-up
