---
dist: bionic
env:
  global:
    - VAGRANT_VERSION="2.2.7"
jobs:
  fast_finish: true
  include:
    - name: "Whitespace error check"
      language: shell
      script: git diff-tree --check $(git hash-object -t tree /dev/null) HEAD
      stage: linting
    - name: "Missing EOF newlines check"
      language: shell
      script: |
        find "$(pwd)" -type f -not -path "*/\.git/*" >tmp; \
        while IFS= read -r file; do \
          case "$(git diff --no-index --numstat /dev/null "$file")" in \
            "$(printf '%s\t-\t' -)"*) echo "skipping newline check for $file because it's a binary"; continue ;; \
            *) echo "Checking $file"; [ -z "$(tail -c1 "$file")" ] || exit 1 ;; \
          esac; \
        done <tmp; \
        rm tmp;
    - name: "hadolint"
      language: shell
      script: |
        find . -name "Dockerfile" -type f -print0 \
        | xargs -0 -I file sh -c 'docker run --rm -i hadolint/hadolint:v1.17.5-8-gc8bf307-alpine < "file"' \
        || exit 1
    - name: kubeval
      language: shell
      script: |
        docker run -t \
          -v "$(pwd)":/kubernetes-playground:ro \
          garethr/kubeval:0.14.0 \
          --strict  -d /kubernetes-playground/kubernetes
    - before_install: gem install travis --no-document
      install: echo "Overriding the default install, to avoid installing gems from the Gemfile"
      name: "Travis lint"
      script: travis lint --skip-completion-check -x
    - name: "Shellcheck"
      language: shell
      script: |
        for file in $(find "$(pwd)" \
          -type f \
          -not -path "*/\.git/*" \
          -not -name "*.md" \
          -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print); do \
            f="${file#$(pwd)}"; \
            f="${f/\//}"; \
            echo "Linting $f"; \
            if [ ! -x "$f" ]; then echo "Error: $f is not executable!"; exit 1; fi \
            docker run -v "$(pwd)":/mnt:ro --rm -t koalaman/shellcheck:v0.7.0 \
              "$f" || exit 1; \
        done;
    - name: "YAMLlint"
      language: shell
      install: sudo pip install -r requirements.txt
      script: yamllint --strict $(git ls-files '*.yaml' '*.yml') || exit 1
    - name: "Markdownlint"
      install: npm install
      language: node_js
      node_js: node
      script: |
        find -name "*.md" -not -path "*/node_modules/*" \
        | xargs markdownlint || exit 1
    - name: "Vagrant validate"
      before_install:
        - sudo scripts/linux/ci/install-libvirt.sh
        - sudo scripts/linux/ci/install-vagrant.sh
        - sudo scripts/linux/ci/install-vagrant-plugins.sh
        - sudo scripts/linux/ci/generate-env-for-travis.sh
        - sudo chown -R travis:travis $HOME/.vagrant.d
      language: shell
      script: vagrant validate --ignore-provider
    - name: "shfmt"
      language: go
      before_install: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      go: "1.14.1"
      script: shfmt -d . || exit 1;
    - name: "ansible-lint"
      before_script: cd ansible || exit 1
      install: sudo pip install -r requirements.txt
      language: shell
      script: |
        ansible-lint -v \
          kubernetes.yml \
          openssl-self-signed-certificate.yml \
        || exit 1
    - name: "Build kitesproject/net-tests container image (final)"
      stage: build_container_images
      language: shell
      before_script: cd docker/kites/net-tests || exit 1
      script: |
        docker build --target final -t kitesproject/net-test .
    - name: "Build kitesproject/net-tests container image (dev)"
      language: shell
      before_script: cd docker/kites/net-tests || exit 1
      script: |
        docker build --target dev -t kitesproject/net-test:latest-dev .
    - name: "Test Kitchen"
      env:
        - VAGRANT_DEFAULT_PROVIDER=libvirt
      stage: test_kitchen
      before_install:
        - sudo scripts/linux/ci/install-libvirt.sh
        - sudo scripts/linux/ci/install-vagrant.sh
        - sudo scripts/linux/ci/install-vagrant-plugins.sh
        # Fix premissions after installing vagrant plugins with sudo
        - sudo chown -R travis:travis $HOME/.vagrant.d
        # This doesn't have effect if you don't open a new shell
        - sudo adduser "$(id -un)" libvirt
        - sudo adduser "$(id -un)" kvm
        - sudo lsmod | sort
        - sudo modprobe -a kvm
      before_script:
        - kvm-ok
        - kitchen diagnose
        - kitchen list
        # Trigger the generation of variable and inventory files
        - vagrant status
      install:
        - gem install bundler
        - bundle install || exit 1
      language: ruby
      # Run with sudo because the libvirt socket is owned by the libvirt group,
      # and the current user was added to the group in the current session,
      # so the membership to that group is not yet in effect.
      # Set the PATH to make the installed gems accessible.
      script: |
        sudo env "PATH=$PATH" kitchen test default-centos-7
language: shell
os: linux
services:
  - docker
stages:
  - linting
  - build_container_images
  - test_kitchen
