---
driver:
  kitchen_cache_directory: .kitchen/cache
  name: vagrant
  synced_folders:
    - [".", "/vagrant"]

platforms:
  - name: centos-7
    driver:
      box: centos/7

provisioner:
  ansible_connection: local
  ansible_extra_flags: "--skip-tags=initialize_kubernetes_cluster"
  ansible_host_key_checking: false
  ansible_version: 2.7.12
  custom_pre_play_command: |
    [ -d /home/vagrant/.ansible ] && sudo chown -R vagrant:vagrant /home/vagrant/.ansible; \
    sudo /vagrant/scripts/linux/check-kubeadm-requirements.sh
  group_vars_path: ansible/group_vars
  host_vars_path: ansible/host_vars
  name: ansible_playbook
  hosts: test-kitchen
  idempotency_skip_tags: ["initialize_kubernetes_cluster"]
  idempotency_test: true
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  roles_path: ansible/roles

suites:
  - name: default
    provisioner:
      playbook: ansible/kubernetes.yml
      role_name: kubernetes
  - name: openssl_self_signed
    provisioner:
      playbook: ansible/openssl-self-signed-certificate.yml
      role_name: openssl_self_signed

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec
