---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-config
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    logLevel = "INFO"
    [api]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [kubernetes]
    [metrics]
      [metrics.prometheus]
