---
kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - nodePort: 80
      protocol: TCP
      port: 80
      name: web
    - nodePort: 443
      protocol: TCP
      port: 443
      name: web-secure
    - protocol: TCP
      port: 8080
      name: admin
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
          - path: /monitoring/ingress
            backend:
              serviceName: traefik-ingress-service
              servicePort: admin
  tls:
    - secretName: traefik-ui-tls-cert
