---
replicas: 1

persistence:
  enabled: true
  size: 0.5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "glusterfs-storage"

adminUser: admin
adminPassword: strongpassword

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        access: proxy
        isDefault: true

grafana.ini:
  server:
    domain: kubernetes-master-1.kubernetes-playground.local
    root_url: "%(protocol)s://%(domain)s/monitoring/cluster/"

ingress:
  enabled: true
  path: /monitoring/cluster
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  hosts:
    - kubernetes-master-1.kubernetes-playground.local
    - kubernetes-minion-1.kubernetes-playground.local
    - kubernetes-minion-2.kubernetes-playground.local
    - kubernetes-minion-3.kubernetes-playground.local

service:
  annotations:
    prometheus.io/scrape: "true"
