---
- name: Add Docker APT repository key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
    state: present
    update_cache: true
