---
- name: Define GlusterFS packages to install
  set_fact:
    ferrarimarco_kubernetes_glusterfs_packages: "{{ __ferrarimarco_kubernetes_glusterfs_packages | list }}"
  when: ferrarimarco_kubernetes_glusterfs_packages is not defined

- name: Install GlusterFS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ferrarimarco_kubernetes_glusterfs_packages }}"

- name: Define kernel modules to laod for GlusterFS
  set_fact:
    ferrarimarco_kubernetes_glusterfs_kernel_modules: "{{ __ferrarimarco_kubernetes_glusterfs_kernel_modules | list }}"
  when: ferrarimarco_kubernetes_glusterfs_kernel_modules is not defined

- name: Load the necessary kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ ferrarimarco_kubernetes_glusterfs_kernel_modules }}"

- name: Add kernel modules to autoload file
  lineinfile:
    create: true
    dest: "{{ ferrarimarco_kubernetes_kernel_modules_conf_dir }}/{{ item }}.conf"
    line: "{{ item }}"
    state: present
    owner: root
    group: root
    mode: 0644
  notify: restart_systemd_modules_load
  with_items: "{{ ferrarimarco_kubernetes_glusterfs_kernel_modules }}"
