---

# systemd-modules-load loads kernel modules at boot
- name: Restart systemd-modules-load
  service:
    name: systemd-modules-load
    enabled: true
    state: restarted
  listen:
    - systemd_modules_load_restart

# daemon_reload loads systemd services configuration
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  listen:
    - systemd_daemon_reload

# Careful with this, because we run Ansible via Docker, so we should not
# restart the docker service while we run Ansible in a Docker container
- name: Restart the Docker service
  service:
    name: docker
    state: restarted
  listen:
    - docker_service_restart
