---
- include: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Enable docker service
  service:
    enabled: true
    name: docker
    state: started

- name: Setup the Docker service
  service:
    name: docker
    state: "{{ docker_service_status|default('started') }}"

- name: Ensure that the Docker group has been created
  group:
    name: docker
    state: present
