---
- include: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Generate Docker daemon configuration file
  become: true
  template:
    backup: false
    dest: /etc/docker/daemon.json
    group: root
    mode: 0755
    owner: root
    src: templates/docker.json.j2
  notify:
    - docker_service_restart

- name: Enable and start docker service
  service:
    enabled: true
    name: docker
    state: started

- name: Ensure that the Docker group has been created
  group:
    name: docker
    state: present
