---
- name: Install Docker dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker APT repository key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: |
      deb https://download.docker.com/linux/debian
      {{ ansible_distribution_release }}
      {{ docker_apt_repository_section_name }}
    # Set the filename because the docker installation scripts adds the same
    # APT repository in this file. Specifying this avoids adding the same
    # repository in a different file.
    filename: docker
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
