---
- hosts: all
  gather_facts: true
  handlers:
    - name: Reload systemd daemon
      become: true
      systemd:
        daemon_reload: true
      listen:
        - systemd_read_configs
  post_tasks:
    - name: Set ansible_ssh_connection_ip_v4_address fact
      set_fact:
        ansible_ssh_connection_ip_v4_address: >-
          "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
      tags:
        - quick_setup
    - name: Get the interface name for Ansible SSH connection interface
      become: true
      changed_when: false
      shell: |
        set -e -o pipefail ; \
        NODE_IP_V4={{ ansible_ssh_connection_ip_v4_address }} ; \
        ip -o addr show | grep $NODE_IP_V4 | awk '{print $2}'
      register: ansible_ssh_connection_interface_name_result
      tags:
        - quick_setup
    - name: Set facts
      set_fact:
        ansible_ssh_connection_interface_name: "{{ ansible_ssh_connection_interface_name_result.stdout }}"
      tags:
        - quick_setup
    - name: Display all variables/facts known for {{ inventory_hostname }}
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 2
    - name: Print debug information
      changed_when: false
      vars:
        msg: |
            Ansible distribution: {{ ansible_distribution }}
            Ansible distribution version: {{ ansible_distribution_version }}
            Ansible domain: {{ ansible_domain }}
            Ansible FQDN: {{ ansible_fqdn }}
            ansible hostname: {{ ansible_hostname }}
            Ansible kernel: {{ ansible_kernel }}
            Ansible user: {{ ansible_user }}
            Ansible SSH connection IPv4 address: {{ ansible_ssh_connection_ip_v4_address }}
            Ansible SSH connection interface name: {{ ansible_ssh_connection_interface_name }}
            Inventory hostname: {{ inventory_hostname }}
            PATH: {{ hostvars[inventory_hostname]['ansible_env']['PATH'] }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: Initialize an IPv6 interface
      become: true
      shell: |
        set -e ; \
        /vagrant/scripts/linux/configure-ipv6-interface.sh \
        {{ ipv6_address }} \
        {{ ansible_ssh_connection_ip_v4_address }} \
        {{ subnet_mask_ipv6 }}
      when: ipv6_address is defined
    - name: Remove FQDN from 127.0.0.1
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: "^127[.]0[.]0[.]1.*{{ assigned_hostname }}"
        owner: root
        group: root
        mode: 0644
        state: absent
      when: assigned_hostname is defined
    - name: Add the FQDN to the hosts file
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ item.ip_v4_address }} {{ item.hostname }}"
        line: "{{ item.ip_v4_address }} {{ item.hostname }}"
        owner: root
        group: root
        mode: 0644
      loop: "{{ ip_to_host_mappings }}"
    - name: Configure registry name resolution in hosts file
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ kubernetes_master_1_ip }} {{ docker_registry_host }}"
        line: "{{ kubernetes_master_1_ip }} {{ docker_registry_host }}"
        owner: root
        group: root
        mode: 0644
      when: docker_registry_host is defined
    - name: Configure Kubelet
      become: true
      template:
        backup: false
        dest: /usr/lib/systemd/system/kubelet.service.d/90-node-ip.conf
        group: root
        mode: 0755
        owner: root
        src: templates/90-node-ip.conf.j2
      notify:
        - systemd_read_configs
      when: "'kubernetes-masters' in group_names or 'kubernetes-minions' in group_names"
    - name: Look up docker cgroup driver
      shell: "set -o pipefail && docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
      register: docker_cgroup_driver
      changed_when: false
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate Kubeadm configuration file
      become: true
      template:
        backup: false
        dest: /tmp/kubeadm-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/kubeadm-config.yaml.j2
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate weavenet configuration file
      become: true
      template:
        backup: false
        dest: /tmp/weavenet-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/weavenet-config.yaml.j2
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate Calico configuration file
      become: true
      template:
        backup: false
        dest: /tmp/calico-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/calico-config.yaml.j2
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Define if_name_for_flannel
      set_fact:
        if_name_for_flannel: "{{ ansible_ssh_connection_interface_name }}"
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate Flannel configuration file
      become: true
      template:
        backup: false
        dest: /tmp/kube-flannel-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/kube-flannel-config.yaml.j2
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - initialize_kubernetes_cluster
        - quick_setup
    - name: Initialize Kubernetes cluster (master)
      become: true
      shell: |
        set -e ; \
        /vagrant/scripts/linux/bootstrap-kubernetes-{{ kubernetes_classifier }}.sh \
        /tmp/kubeadm-config.yaml \
        {{ kubernetes_network_plugin }}
      args:
        creates: /home/vagrant/.kube/config
      when: inventory_hostname == kubernetes_master_1_ip
      tags:
        - initialize_kubernetes_cluster
        - quick_setup
    - name: Enable kubectl autocompletion (master)
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "source <(kubectl completion bash)"
        owner: vagrant
      when: inventory_hostname == kubernetes_master_1_ip
    - name: Initialize Kubernetes cluster (workers)
      become: true
      shell: |
        /vagrant/scripts/linux/bootstrap-kubernetes-{{ kubernetes_classifier }}.sh \
        {{ kubernetes_master_1_ip }} \
        {{ kubeadm_token }} \
        {{ cluster_ip_cidr }} \
        {{ kubernetes_network_plugin }}
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: "'kubernetes-minions' in group_names"
      tags:
        - quick_setup
    - name: Download gluster-kubernetes
      become: true
      unarchive:
        creates: /opt/gluster-kubernetes-master/deploy/gk-deploy
        dest: /opt
        remote_src: true
        src: https://github.com/gluster/gluster-kubernetes/archive/master.zip
      when: "'kubernetes-masters' in group_names"
    - name: check for installation of helm
      become: true
      stat:
        path: '{{ kubernetes_helm_install_dir }}'
      changed_when: false
      register: kubernetes_helm_binary_dir
    - when: not kubernetes_helm_binary_dir.stat.exists
      block:
        - name: Install unarchive packages
          become: true
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - bzip2
            - gzip
            - tar
            - unzip
            - xz
        - name: Download helm
          become: true
          get_url:
            url: '{{ kubernetes_helm_url }}'
            dest: /tmp/{{ kubernetes_helm_archive }}
            checksum: '{{ kubernetes_helm_checksum }}'
            mode: 0644
        - name: Create helm install directory
          become: true
          file:
            path: '{{ kubernetes_helm_install_dir }}'
            state: directory
            mode: 0755
        - name: Unarchive helm
          become: true
          unarchive:
            copy: false
            src: /tmp/{{ kubernetes_helm_archive }}
            dest: '{{ kubernetes_helm_install_dir }}'
            creates: '{{ kubernetes_helm_install_dir }}/{{ kubernetes_helm_platform }}'
      always:
        - name: Cleanup helm installer
          become: true
          file:
            path: /tmp/{{ kubernetes_helm_archive }}
            state: absent
        - name: Link helm binary
          become: true
          with_items:
            - helm
          file:
            src: '{{ kubernetes_helm_install_dir }}/{{ kubernetes_helm_platform }}/{{ item }}'
            dest: '{{ kubernetes_helm_bin_dir }}/{{ item }}'
            state: link
  roles:
    - role: docker
      become: true
    - role: kubernetes
      become: true
      ferrarimarco_kubernetes_filesystem: glusterfs
  vars:
    kubernetes_helm_platform: '{{ kubernetes_helm_os }}-{{ kubernetes_helm_arch }}'
    kubernetes_helm_name: helm-{{ kubernetes_helm_ver }}-{{ kubernetes_helm_platform }}
    kubernetes_helm_archive: '{{ kubernetes_helm_name }}.{{ kubernetes_helm_archive_type }}'
    kubernetes_helm_url: '{{ kubernetes_helm_mirror }}/{{ kubernetes_helm_archive }}'
    kubernetes_helm_install_dir: '{{ kubernetes_helm_bin_dir }}/helm-{{ kubernetes_helm_ver }}'
    kubernetes_helm_checksum: '{{ kubernetes_helm_checksums[kubernetes_helm_ver][kubernetes_helm_platform] }}'
