---
- hosts: all
  any_errors_fatal: true
  gather_facts: true
  handlers:
    - name: Reload systemd daemon
      become: true
      systemd:
        daemon_reload: true
      listen:
        - systemd_read_configs
  post_tasks:
    - name: Set ansible_ssh_connection_ip_v4_address fact
      set_fact:
        ansible_ssh_connection_ip_v4_address: >-
          {{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}
      tags:
        - quick_setup
    - name: Get the interface name for Ansible SSH connection interface
      become: true
      changed_when: false
      shell: |
        set -e -o pipefail ; \
        ip -o addr show | grep {{ ansible_ssh_connection_ip_v4_address }} | awk '{print $2}'
      register: ansible_ssh_connection_interface_name_result
      tags:
        - quick_setup
    - name: Look up docker cgroup driver
      shell: "set -o pipefail && docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
      register: docker_cgroup_driver_result
      changed_when: false
      tags:
        - quick_setup
    - name: Set facts
      set_fact:
        ansible_ssh_connection_interface_name: "{{ ansible_ssh_connection_interface_name_result.stdout }}"
        docker_cgroup_driver: "{{ docker_cgroup_driver_result.stdout }}"
      tags:
        - quick_setup
    - name: Get the NetworkManager connection UUID for the {{ ansible_ssh_connection_interface_name }} connection
      become: true
      changed_when: false
      shell: |
        set -e -o pipefail ; \
        nmcli -g UUID,DEVICE con show | grep {{ ansible_ssh_connection_interface_name }} | awk -F ":" '{print $1}'
      register: ansible_ssh_connection_nm_connection_name_result
      tags:
        - quick_setup
    - name: Set facts
      set_fact:
        ansible_ssh_connection_nm_connection_name: "{{ ansible_ssh_connection_nm_connection_name_result.stdout }}"
      tags:
        - quick_setup
    - name: Display all variables/facts known for {{ inventory_hostname }}
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 2
    - name: Print debug information
      changed_when: false
      vars:
        msg: |
            Ansible distribution: {{ ansible_distribution }}
            Ansible distribution version: {{ ansible_distribution_version }}
            Ansible domain: {{ ansible_domain }}
            Ansible FQDN: {{ ansible_fqdn }}
            ansible hostname: {{ ansible_hostname }}
            Ansible kernel: {{ ansible_kernel }}
            Ansible user: {{ ansible_user }}
            Ansible SSH connection IPv4 address: {{ ansible_ssh_connection_ip_v4_address }}
            Ansible SSH connection interface name: {{ ansible_ssh_connection_interface_name }}
            Ansible SSH connection Networkmanager UUID: {{ ansible_ssh_connection_nm_connection_name }}
            Cluster IP CIDR: {{ cluster_ip_cidr }}
            Docker cgroup driver: {{ docker_cgroup_driver }}
            Inventory hostname: {{ inventory_hostname }}
            IPv6 address: {{ ipv6_address | default('NOT DEFINED') }}
            Kubeadm token: {{ kubeadm_token }}
            Kubernetes master 1 hostname: {{ kubernetes_master_1_hostname }}
            Kubernetes master 1 IP: {{ kubernetes_master_1_ip }}
            Kubernetes network plugin: {{ kubernetes_network_plugin }}
            PATH: {{ hostvars[inventory_hostname]['ansible_env']['PATH'] }}
            Service IP CIDR: {{ service_ip_cidr }}
            Subnet mask IPv6: {{ subnet_mask_ipv6 }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: Add an IPv6 address to {{ ansible_ssh_connection_interface_name }}
      become: true
      shell: |
        set -e ; \
        /vagrant/scripts/linux/configure-ipv6-interface.sh \
        {{ ipv6_address }} \
        {{ subnet_mask_ipv6 }} \
        {{ ansible_ssh_connection_interface_name }} \
        {{ ansible_ssh_connection_nm_connection_name }}
      when: ipv6_address is defined
    - name: Remove FQDN from 127.0.0.1
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: "^127[.]0[.]0[.]1.*{{ assigned_hostname }}"
        owner: root
        group: root
        mode: 0644
        state: absent
      when: assigned_hostname is defined
    - name: Add the FQDN to the hosts file
      become: true
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ item.ip_v4_address }} {{ item.hostname }}"
        line: "{{ item.ip_v4_address }} {{ item.hostname }}"
        owner: root
        group: root
        mode: 0644
      loop: "{{ ip_to_host_mappings }}"
    - name: Configure Kubelet
      become: true
      template:
        backup: false
        dest: /usr/lib/systemd/system/kubelet.service.d/90-node-ip.conf
        group: root
        mode: 0755
        owner: root
        src: templates/90-node-ip.conf.j2
      notify:
        - systemd_read_configs
      when: "'kubernetes-masters' in group_names or 'kubernetes-minions' in group_names"
    - name: Generate Kubeadm configuration file
      become: true
      template:
        backup: false
        dest: /tmp/kubeadm-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/kubeadm-config.yaml.j2
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate weavenet configuration file
      become: true
      template:
        backup: false
        dest: /tmp/weavenet-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/weavenet-config.yaml.j2
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate Calico configuration file
      become: true
      template:
        backup: false
        dest: /tmp/calico-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/calico-config.yaml.j2
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Define if_name_for_flannel
      set_fact:
        if_name_for_flannel: "{{ ansible_ssh_connection_interface_name }}"
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - quick_setup
    - name: Generate Flannel configuration file
      become: true
      template:
        backup: false
        dest: /tmp/kube-flannel-config.yaml
        group: root
        mode: 0755
        owner: root
        src: templates/kube-flannel-config.yaml.j2
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - initialize_kubernetes_cluster
        - quick_setup
    - name: Initialize Kubernetes cluster (master)
      become: true
      shell: |
        set -e ; \
        /vagrant/scripts/linux/bootstrap-kubernetes-{{ kubernetes_classifier }}.sh \
        /tmp/kubeadm-config.yaml \
        {{ kubernetes_network_plugin }}
      args:
        creates: /home/vagrant/.kube/config
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
      tags:
        - initialize_kubernetes_cluster
        - quick_setup
    - name: Enable kubectl autocompletion (master)
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "source <(kubectl completion bash)"
        owner: vagrant
      when: ansible_ssh_connection_ip_v4_address == kubernetes_master_1_ip
    - name: Initialize Kubernetes cluster (workers)
      become: true
      shell: |
        /vagrant/scripts/linux/bootstrap-kubernetes-{{ kubernetes_classifier }}.sh \
        {{ kubernetes_master_1_ip }} \
        {{ kubeadm_token }} \
        {{ cluster_ip_cidr }} \
        {{ kubernetes_network_plugin }}
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: "'kubernetes-minions' in group_names"
      tags:
        - quick_setup
  roles:
    - role: docker
      become: true
    - role: kubernetes
      become: true
  vars:
    kubernetes_helm_platform: '{{ kubernetes_helm_os }}-{{ kubernetes_helm_arch }}'
    kubernetes_helm_name: helm-{{ kubernetes_helm_ver }}-{{ kubernetes_helm_platform }}
    kubernetes_helm_archive: '{{ kubernetes_helm_name }}.{{ kubernetes_helm_archive_type }}'
    kubernetes_helm_url: '{{ kubernetes_helm_mirror }}/{{ kubernetes_helm_archive }}'
    kubernetes_helm_install_dir: '{{ kubernetes_helm_bin_dir }}/helm-{{ kubernetes_helm_ver }}'
    kubernetes_helm_checksum: '{{ kubernetes_helm_checksums[kubernetes_helm_ver][kubernetes_helm_platform] }}'
