---
- hosts: all
  gather_facts: true
  tasks:
    - name: Set cert paths
      set_fact:
        registry_cert_path: "/etc/docker/certs.d/{{ docker_registry_host }}"
        self_signed_cert_path: /opt/tls/self_signed
    - name: Set openSSL paths
      set_fact:
        openssl_crt_path: "{{ self_signed_cert_path }}/tls.crt"
        openssl_csr_path: "{{ self_signed_cert_path }}/tls.csr"
        openssl_key_path: "{{ self_signed_cert_path }}/tls.key"
    - name: Generate an OpenSSL private key for Docker Registry
      delegate_to: localhost
      openssl_privatekey:
        force: false
        path: "{{ openssl_key_path }}"
        size: 4096
        type: RSA
      run_once: true
    - name: Generate an OpenSSL CSR for Ingress and Docker Registry
      delegate_to: localhost
      openssl_csr:
        common_name: "{{ wildcard_domain }}"
        country_name: IT
        email_address: fake@email.tld
        locality_name: Rome
        organization_name: Org
        organizational_unit_name: Ou
        path: "{{ openssl_csr_path }}"
        privatekey_path: "{{ openssl_key_path }}"
        state_or_province_name: Lazio
      run_once: true
    - name: >-
        Generate a Self Signed OpenSSL certificate forIngress and Docker
        Registry
      delegate_to: localhost
      openssl_certificate:
        csr_path: "{{ openssl_csr_path }}"
        path: "{{ openssl_crt_path }}"
        privatekey_path: "{{ openssl_key_path }}"
        provider: selfsigned
      run_once: true
    - name: Ensure directories exist for self-signed TLS certs
      become: true
      file:
        group: root
        owner: root
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ self_signed_cert_path }}"
    - name: Ensure directories exist for Docker registry self-signed TLS certs
      become: true
      file:
        group: root
        owner: root
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ registry_cert_path }}"
    - name: Copy key, CSR, CRT to master
      become: true
      copy:
        dest: "{{ item.destination }}"
        group: root
        owner: root
        mode: 0644
        src: "{{ item.source }}"
      with_items:
        - source: "{{ openssl_crt_path }}"
          destination: "{{ self_signed_cert_path }}/tls.crt"
        - source: "{{ openssl_csr_path }}"
          destination: "{{ self_signed_cert_path }}/tls.csr"
        - source: "{{ openssl_key_path }}"
          destination: "{{ self_signed_cert_path }}/tls.key"
      when: "'kubernetes-masters' in group_names"
    - name: Configure self-signed TLS certificate for Docker Registry
      become: true
      copy:
        dest: "{{ item.destination }}"
        group: root
        owner: root
        mode: 0600
        src: "{{ item.source }}"
      with_items:
        - source: "{{ openssl_crt_path }}"
          destination: "{{ registry_cert_path }}/ca.crt"
